### ISSUE TITLE
possible to allow salves via a url?

### ISSUE THREAD

**Issue by matthewford** [teespring/active_record_replica#2]
Hi,
Is it possible to connect to slaves via 
```
  slave:
    adapter:   mysql2
    url: <%= ENV['DATABASE_SLAVE_URL'] %>

```
Im seeing this error NoMethodError: undefined method `[]' for nil:NilClass active_record_slave-1.3.0/lib/active_record_slave/active_record_slave.rb:20:in `install!'

**Comment by reidmorrison** [comment]
Yes, this should work with the latest code.
