### ISSUE TITLE
Sometimes sending request to salve during update_attributes 

### ISSUE THREAD

**Issue by matthewford** [teespring/active_record_replica#4]
Hello, 

I'm seeing errors like the following occasionally:

`ActiveRecord::StatementInvalid: Mysql2::Error: The MySQL server is running with the --read-only option so it cannot execute this statement: INSERT INTO ...
`

When calling `update_attributes`

**Comment by reidmorrison** [comment]
Can you submit the complete stack trace, as well as Rails Version?

**Comment by hishammalik** [comment]
@reidmorrison getting error in Rails 5.1 with this call: 

`Order.includes(:store).lock(true).find_by!(number:` params[:id])

Error in log generated is:
`ActiveRecord::StatementInvalid (PG::ReadOnlySqlTransaction: ERROR:  cannot execute SELECT FOR UPDATE in a read-only transaction

**Comment by reidmorrison** [comment]
If you can submit the complete stack trace we can use it to find which method needs to be intercepted or excluded for the patching to work. Otherwise just workaround it by using a `ActiveRecordReplica.read_from_master` block
