### ISSUE TITLE
AR Slave forces a DB connection on precompile

### ISSUE THREAD

**Issue by jnylen** [teespring/active_record_replica#5]
Hi,
After I added AR Slave gem to my project and database.yml it fails due to this gem now requiring DB connection during ``RAILS_ENV=production bundle exec rake assets:precompile``.

It wasn't required before.

Any ideas?

**Comment by jnylen** [comment]
Fixed it will nulldb on test/build.

**Comment by philipgiuliani** [comment]
Same error occurs for me. Can this be prevented?

**Comment by nickmacavoy** [comment]
The fix exists in this fork FYI: https://github.com/AirPR/active_record_slave

**Comment by reidmorrison** [comment]
@joshuapinter @aliahmed922 @abelorian @mattprivman @nickmacavoy @philipgiuliani @jnylen @rajagopals
We no longer need or use the Active Record Slave gem and I was planning on archiving this repository.
Is anyone interested in taking it over? I can send you the github repository
and assign you push privileges on RubyGems to keep posting updated gems.

**Comment by joshuapinter** [comment]
@reidmorrison Thanks for asking for a new maintainer. We are off this gem now because it was preventing proper caching with AR. We are going to wait until we upgrade to Rails 6 and use the native configuration they have there. Cheers. 👍
